# 设置服务器端口
server:
  port: 8080
# 数据库连接配置
spring:
  datasource:
    # MySQL数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接URL，包含连接参数
    url: jdbc:mysql://localhost:3306/charge?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
#驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml